paths:
  clips: path/to/clips
  subtitles: path/to/subtitles
  vector_store: path/to/vector_store
  raw_videos: path/to/raw_videos

openai:
  api_key: [OPENAI_API_KEY]
  models:
    embedding: text-embedding-3-small
    chat: gpt-4-turbo
    temperature: 1.0
    max_tokens: 100
    presence_penalty: 0.6
    frequency_penalty: 0.6  

vector_store:
  collection_name: star_trek_dialog
  similarity_metric: cosine

dialog:
  enable_history: true
  max_history: 10

modes:
  auto_dialog:
    enabled: true
    delay_between_responses: 0.0
    max_exchanges: 10
    max_history: 10
  interactive:
    enabled: true
    max_history: 10
