"""add clip url column

Revision ID: 3c52053ec023
Revises: 41f5dc875814
Create Date: 2025-02-06 16:42:44.861479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c52053ec023'
down_revision: Union[str, None] = '41f5dc875814'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('clip_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'clip_url')
    # ### end Alembic commands ###
